var macro; 
macro =  "CODE:";
macro +=  "VERSION BUILD=8970419 RECORDER=FX" + "\n";
macro +=  "PROMPT \"DATA BARIS KE:\" loop" + "\n";
macro +=  "SET !ERRORIGNORE YES" + "\n";
macro +=  "SET !LOOP {{loop}}" + "\n";
macro +=  "SET !DATASOURCE akunig1.csv" + "\n";
macro +=  "SET !DATASOURCE_LINE {{!LOOP}}" + "\n";
macro +=  "SET !DATASOURCE_COLUMNS 5" + "\n";
macro +=  "SET !TIMEOUT_PAGE 60" + "\n";
macro +=  "URL GOTO=https://www.instagram.com/" + "\n";
macro +=  "TAG POS=1 TYPE=BUTTON ATTR=TXT:Sign<SP>up<SP>with<SP>email<SP>or<SP>phone<SP>number" + "\n";
macro +=  "WAIT SECONDS=1" + "\n";
macro +=  "TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:NoFormName ATTR=ID:*&&name:emailOrPhone CONTENT={{!COL1}}" + "\n";
macro +=  "WAIT SECONDS=1" + "\n";
macro +=  "TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:NoFormName ATTR=ID:*&&name:fullName CONTENT={{!COL2}}" + "\n";
macro +=  "WAIT SECONDS=1" + "\n";
macro +=  "TAG POS=1 TYPE=INPUT:TEXT FORM=NAME:NoFormName ATTR=ID:*&&name:username CONTENT={{!COL3}}" + "\n";
macro +=  "WAIT SECONDS=1" + "\n";
macro +=  "SET !ENCRYPTION NO" + "\n";
macro +=  "TAG POS=1 TYPE=INPUT:PASSWORD FORM=NAME:NoFormName ATTR=ID:*&&name:password CONTENT={{!COL4}}" + "\n";
macro +=  "WAIT SECONDS=5" + "\n";
macro +=  "TAG POS=1 TYPE=BUTTON FORM=NAME:NoFormName ATTR=TXT:Sign<SP>up" + "\n";
macro +=  "WAIT SECONDS=5" + "\n";
macro +=  "TAG POS=1 TYPE=BUTTON ATTR=TXT:Skip" + "\n";
macro +=  "WAIT SECONDS=2" + "\n";
macro +=  "TAG POS=2 TYPE=BUTTON ATTR=TXT:Skip" + "\n";
macro +=  "WAIT SECONDS=2" + "\n";
macro +=  "TAG POS=3 TYPE=BUTTON ATTR=TXT:Skip" + "\n";
iimPlay(macro)